import Head from 'next/head';
import Sidebar from '@/components/Sidebar';
import { Open_Sans } from '@next/font/google';
import Dashboard from '@/components/Dashboard';
import MovieContext from '../context/showDetailsContext';
const sans = Open_Sans({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MovieContext>
        <main className={`flex ${sans.className}`}>
          <Sidebar />
          <Dashboard />
        </main>
      </MovieContext>
    </>
  );
}
